---
- name: Creating necessary folders
  ansible.builtin.file:
    path: "{{ machikiflix_arr_folder }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Creating necessary folders
  ansible.builtin.file:
    path: "{{ machikiflix_pinchflat_folder }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Créer l'arborescence pour les médias (Torrents, Usenet, Media)
  ansible.builtin.file:
    path: "/data/{{ item }}"
    state: directory
    mode: '0755'
    owner: 1000
    group: 1000
    recurse: false
  loop:
    # Torrents
    - torrents/books
    - torrents/movies
    - torrents/music
    - torrents/tv
    # Usenet
    - usenet/incomplete
    - usenet/complete/books
    - usenet/complete/movies
    - usenet/complete/music
    - usenet/complete/tv
    # Media
    - media/books
    - media/movies
    - media/music
    - media/tv

- name: Deploy update CA certs init script
  ansible.builtin.template:
    src: update-certs.sh.j2
    dest: "{{ machikiflix_arr_folder }}/update-certs.sh"
    owner: root
    group: root
    mode: '0755'


- name: Deploy traefik
  ansible.builtin.include_tasks:
    file: roles/machikiflix/tasks/traefik_deploy.yml

- name: Deploy servarr apps
  ansible.builtin.include_tasks:
    file: roles/machikiflix/tasks/servarr_deploy.yml

- name: Deploy torrent apps
  ansible.builtin.include_tasks:
    file: roles/machikiflix/tasks/torrent_deploy.yml

- name: Deploy media server apps
  ansible.builtin.include_tasks:
    file: roles/machikiflix/tasks/media_server_deploy.yml

