- name: Ensure traefik directories exists
  ansible.builtin.file:
    path: "{{ machikiflix_traefik_folder }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy traefik configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart traefik service
  loop:
    - { src: "docker-compose-traefik.yml", dest: "{{ machikiflix_traefik_folder }}/docker-compose.yml"}
    - { src: "traefik.yml", dest: "{{ machikiflix_traefik_folder }}/traefik.yml" }

- name: Create systemd service for traefik
  ansible.builtin.template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart traefik service
