---
- name: Include vault variables from pki role
  ansible.builtin.include_vars:
    file: roles/pki/vars/vault.yml
  delegate_to: localhost

- name: Ensure certificate directory exists
  ansible.builtin.file:
    path: "{{ haproxy_cert_dir }}"
    state: directory
    # owner: haproxy
    # group: haproxy
    mode: '0750'

- name: Ensure step-ca directory exists
  ansible.builtin.file:
    path: "{{ haproxy_step_ca_path }}"
    state: directory
    mode: '0750'

- name: Write provisioner password to a file
  ansible.builtin.copy:
    content: "{{ pki_step_ca_provider_password }}"
    dest: "{{ haproxy_step_ca_path }}/provisioner_password.txt"
    mode: '0600'
  no_log: true

- name: Generate certificate and key
  ansible.builtin.command: >
    step ca certificate "*.guerande.local.net"
    "{{ haproxy_cert_dir }}/wildcard.guerande.local.net.crt"
    "{{ haproxy_cert_dir }}/wildcard.guerande.local.net.key"
    --provisioner homelab-acme
    --provisioner-password-file "{{ haproxy_step_ca_path }}/provisioner_password.txt"
  changed_when: true

- name: Combine cert and key into a single PEM file for HAProxy
  ansible.builtin.shell: "cat {{ haproxy_cert_dir }}/wildcard.guerande.local.net.crt {{ haproxy_cert_dir }}/wildcard.guerande.local.net.key > {{ haproxy_cert_path }}"
  changed_when: true
