plugin: community.general.proxmox
url: "{{ (lookup('ansible.builtin.unvault', 'inventories/group_vars/all/proxmox.yaml') | ansible.builtin.from_yaml).proxmox_readonly_url }}"
user: "{{ (lookup('ansible.builtin.unvault', 'inventories/group_vars/all/proxmox.yaml') | ansible.builtin.from_yaml).proxmox_readonly_user }}"
token_id: "{{ (lookup('ansible.builtin.unvault', 'inventories/group_vars/all/proxmox.yaml') | ansible.builtin.from_yaml).proxmox_readonly_token_id }}"
token_secret: "{{ (lookup('ansible.builtin.unvault', 'inventories/group_vars/all/proxmox.yaml') | ansible.builtin.from_yaml).proxmox_readonly_token_secret }}"
want_facts: true
validate_certs: false
want_proxmox_nodes_ansible_host: false
# Create group with a prefix based on all the tags define on LXC and VM on proxmox
keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
    prefix: group_
# It seems that using filter doesn't work in the compose of the proxmox plugin. I will therefore be using two inventories, one for LXC and one for VM
compose:
  ansible_host: proxmox_ipconfig0.ip.split('/')[0]
  custom_hostname: proxmox_name