plugin: community.general.proxmox
url: "{{ (lookup('ansible.builtin.unvault', 'inventories/group_vars/all/proxmox.yaml') | ansible.builtin.from_yaml).proxmox_readonly_url }}"
user: "{{ (lookup('ansible.builtin.unvault', 'inventories/group_vars/all/proxmox.yaml') | ansible.builtin.from_yaml).proxmox_readonly_user }}"
token_id: "{{ (lookup('ansible.builtin.unvault', 'inventories/group_vars/all/proxmox.yaml') | ansible.builtin.from_yaml).proxmox_readonly_token_id }}"
token_secret: "{{ (lookup('ansible.builtin.unvault', 'inventories/group_vars/all/proxmox.yaml') | ansible.builtin.from_yaml).proxmox_readonly_token_secret }}"
want_facts: true
validate_certs: false
# Create group with a prefix based on all the tags define on LXC and VM on proxmox
keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
    prefix: group_
# Add custom variable using lookup to a group. Here we set ansible facts gather of the LXC/VM (want_facts need to be set to true)
# The first part retrieve the ip for an LXC and the second part for a VM
compose:
  ansible_host: proxmox_net0.ip 
# | default(proxmox_agent_interfaces[1].ip-addresses[0])