- name: Install basics requirements for Docker-CE
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes

- name: Add GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
  become: yes

- name: Add docker apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu   focal stable
    update_cache: yes
  become: yes

- name: Install Docker CE
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: yes

- name: Ensure group "docker"
  ansible.builtin.group:
    name: docker
    state: present
  become: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Reset connection so docker group is picked up.
  meta: reset_connection